title: Sean Adams
description: Portfolio website 
url: "https://SeanAdams124.github.io"  # no trailing slash
baseurl: "/professional-website"                            # leading slash required

# Choose ONE of these (theme OR remote_theme):
# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown

# Helps the github-metadata plugin:
repository: estillcountyatc-computerscience/portfolio-template
